name: CI

on:
  pull_request:
    types:
      - opened
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    environment: Stable
    env:
      PR_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4
        name: Derive appropriate SHAs for base and head for `nx affected` commands

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 22.6.0
          cache: 'npm'

      # This should really go into a separate command, then environments for non-prod prod
      # But, because this is just me pushing out to one space - going to change this in the future.
      - run: |
          echo "NODE_ENV=development" >> $GITHUB_ENV
          npm install
          npx playwright install --with-deps

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      - name: Run Linter
        run: npx nx affected:lint --base=$NX_BASE --head=$NX_HEAD
      - name: Run Tests
        run: npx nx affected:test --base=$NX_BASE --head=$NX_HEAD
      - name: Run E2E
        run: npx nx affected --parallel 1 -t e2e --base=$NX_BASE --head=$NX_HEAD
